#config.yaml 
paths:
  processed_data_dir: "data/processed"
  raw_data_root: "data/raw"
  outputs_dir: "outputs"
  config_file_path: "config/config.yaml"

dataset:
  train_split_ration: 0.9 
  random_seed: 42
  max_stroke_len: 1200 
  max_text_len: 80 
  offset_filter_threshold: 60

model_params:
  lstm_size: 400 
  output_mixture_components: 20 
  attention_mixture_components: 10 
  dropout_prob: 0.15
  eps: 0.00000001 # 1e-8 
  sigma_eps: 0.001 # 1e-4

training_params:
  batch_sizes: [64, 96, 128]
  learning_rates: [0.001, 0.0005, 0.0002]
  beta1_decays: [0.9, 0.95, 0.98]
  weight_decay: 0.00001
  patiences: [2000, 1500, 1000] 
  optimizer_type: "adam" 
  grad_clip: 5.0
  num_training_steps: 100000
  log_interval: 10

prediction_params:
  max_length: 1200

wandb:
  enabled: true
  project_name: "Scriptify"
  tags: ['second_model_arch', 'scriptify']
  log_model_checkpoint_freq: 0 # just mean log best model only 
  watch_model_log_freq: 100
